# Site settings
title: Michelin Munchies
author: Jackson Kearl
email: MichelinMunchies@mit.edu
description: >-
  Delicious tidbits of the Jackson Kearl lifestyle.
  Posts on my thoughts and experiences regarding travel, food, code, etc.
baseurl: ""
url: "https://michelinmunchies.com"
twitter_username: JacksonKearl
github_username:  jacksonkearl

disqus:
  shortname: michelinmunchies

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
